projects:
  nyc_taxi:
    schema: nyc_taxi
    description: NYC yellow taxi trip records
    tables:
      trip_data:
        sources:
          - yellow_tripdata_2025-01.parquet
          - yellow_tripdata_2025-02.parquet
          - yellow_tripdata_2025-03.parquet

  addresses:
    schema: addresses
    description: Reference data for cities and addresses
    tables:
      cities:
        source: cities.csv
        columns:
          - name: city
            type: text
      addresses:
        source: addresses.csv
