version: 2

models:
  - name: trip_data_bronze
    description: "NYC taxi trip data with column names transformed to lower and snake case"
    columns:
      - name: vendor_id
        description: "Taxi vendor identifier"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: tpep_pickup_datetime
        description: "Pickup timestamp"
        tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: "Dropoff timestamp"
        tests:
          - not_null
      - name: passenger_count
        description: "Number of passengers"
      - name: trip_distance
        description: "Distance traveled in miles"
      - name: ratecode_id
        description: "Rate code"
      - name: store_and_fwd_flag
        description: "Store and forward flag"
        tests:
          - accepted_values:
              values: ["Y", "N"]
      - name: pu_location_id
        description: "Pickup location ID"
      - name: do_location_id
        description: "Dropoff location ID"
      - name: payment_type
        description: "Payment type code"
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: congestion_surcharge
      - name: airport_fee
      - name: cbd_congestion_fee
  - name: trip_data_silver
    description: "Silver table copied from bronze NYC Taxi trip_data"
    columns:
      - name: vendor_id
      - name: tpep_pickup_datetime
      - name: tpep_dropoff_datetime
      - name: passenger_count
      - name: trip_distance
      - name: ratecode_id
      - name: store_and_fwd_flag
      - name: pu_location_id
      - name: do_location_id
      - name: payment_type
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: congestion_surcharge
      - name: airport_fee
      - name: cbd_congestion_fee
