version: 2

models:
  - name: trip_data_silver
    description: "Silver table copied from bronze NYC Taxi trip_data"
    columns:
      - name: VendorID
        description: "Taxi vendor identifier"
#        tests:
#          - not_null
#          - unique
#          - dbt_expectations.expect_column_values_to_be_of_type:
#              column_type: integer
      - name: tpep_pickup_datetime
        description: "Pickup timestamp"
        tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: "Dropoff timestamp"
        tests:
          - not_null
      - name: passenger_count
        description: "Number of passengers"
      - name: trip_distance
        description: "Distance traveled in miles"
      - name: RatecodeID
        description: "Rate code"
      - name: store_and_fwd_flag
        description: "Store and forward flag"
        tests:
          - accepted_values:
              values: ["Y", "N"]
      - name: PULocationID
        description: "Pickup location ID"
      - name: DOLocationID
        description: "Dropoff location ID"
      - name: payment_type
        description: "Payment type code"
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: congestion_surcharge
      - name: Airport_fee
      - name: cbd_congestion_fee
